AWSTemplateFormatVersion: 2010-09-09
#------------------------------------------------------
#  Parameter
#------------------------------------------------------
Parameters: 
  ProjectName:
    Type: String
    Default: simple-nginx
    Description: ProjectName
  SSHAllowAddress:
    Type: String
    Default: 0.0.0.0/0
#------------------------------------------------------
#  security Group
#------------------------------------------------------
Resources: 
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22, 80
      VpcId: 
        Fn::ImportValue: !Sub ${ProjectName}-vpc
      SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: !Ref SSHAllowAddress
          - IpProtocol: tcp
            FromPort: 80
            ToPort: 80
            CidrIp: 0.0.0.0/0
#------------------------------------------------------
#  NetworkACL
#------------------------------------------------------
  NetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
        VpcId:
          Fn::ImportValue: !Sub ${ProjectName}-vpc
        Tags:
        - Key: stack
          Value: develop
#------------------------------------------------------
#  Inbound NetwokACL
#------------------------------------------------------
  InboundSSHNetworkAclEntry: 
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref NetworkAcl
      Egress: false
      RuleNumber: 100
      Protocol: 6 #TCP
      RuleAction: allow
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 22
        To: 22
  InboundHTTPNetworkAclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref NetworkAcl
      Egress: false
      RuleNumber: 101
      Protocol: 6 #TCP
      RuleAction: allow
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 80
        To: 80
  InboundResponseNetworkAclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref NetworkAcl
      Egress: false
      RuleNumber: 104
      Protocol: 6 #TCP
      RuleAction: allow
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 1024
        To: 65535
#------------------------------------------------------
#  Outbound NetwokACL
#------------------------------------------------------
  OutboundHTTPNetworkAclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref NetworkAcl
      Egress: true
      RuleNumber: 100
      Protocol: 6 #TCP
      RuleAction: allow
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 80
        To: 80
  OutboundHTTPSNetworkAclEntry: 
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref NetworkAcl
      Egress: true
      RuleNumber: 101
      Protocol: 6 #TCP
      RuleAction: allow
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 443
        To: 443
  OutboundResponseNetworkAclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref NetworkAcl
      Egress: true
      RuleNumber: 102
      Protocol: 6 #TCP
      RuleAction: allow
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 1024
        To: 65535
#------------------------------------------------------
#  SubnetACL
#------------------------------------------------------         
  SubnetNetworkAclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId:
        Fn::ImportValue: !Sub ${ProjectName}-publicsubnet
      NetworkAclId:
        !Ref NetworkAcl
#------------------------------------------------------
#  Output
#------------------------------------------------------           
Outputs:
  StackSecurityGroup:
    Description:  Security Group ID
    Value: !Ref SecurityGroup
    Export:
      Name: !Sub ${ProjectName}-sg
